In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("C:/Users/vaishnavi/Downloads/Fintech_Capstone_Project/data/raw/07_scheme_performance.csv")

In [3]:
print(data.shape)

(40, 19)

In [4]:
print(data.dtypes)

amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

In [5]:
data.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [6]:
print(data.columns.tolist())

['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

In [7]:
return_cols = ['return_1yr_pct','return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct']

In [12]:
for col in return_cols:
    data[col] = pd.to_numeric(data[col], errors='coerce')
    print(f"{col} - nulls after conversion: {data[col].isnull().sum()}")

return_1yr_pct - nulls after conversion: 0
return_3yr_pct - nulls after conversion: 0
return_5yr_pct - nulls after conversion: 0
benchmark_3yr_pct - nulls after conversion: 0

In [14]:
data['sharpe_ratio'] = pd.to_numeric(data['sharpe_ratio'], errors='coerce')

In [16]:
negative_sharpe = data[data['sharpe_ratio']<0]
print(f"Funds with negative sharpe ratio:{len(negative_sharpe)}")

Funds with negative sharpe ratio:0

In [19]:
data['negative_Sharpe_flag'] = data['sharpe_ratio']<0
data[['scheme_name','sharpe_ratio','negative_Sharpe_flag']].head(10)

,scheme_name,sharpe_ratio,negative_Sharpe_flag
0,SBI Bluechip Fund - Regular Plan - Growth,0.88,False
1,SBI Bluechip Fund - Direct Plan - Growth,0.81,False
2,SBI Small Cap Fund - Regular Plan - Growth,0.94,False
3,SBI Small Cap Fund - Direct Plan - Growth,0.93,False
4,SBI Magnum Gilt Fund - Regular Plan - Growth,1.52,False
5,HDFC Top 100 Fund - Regular Plan - Growth,1.06,False
6,HDFC Top 100 Fund - Direct Plan - Growth,0.96,False
7,HDFC Mid-Cap Opportunities Fund - Regular - Gr...,0.87,False
8,HDFC Mid-Cap Opportunities Fund - Direct - Growth,0.80,False
9,HDFC Short Term Debt Fund - Regular - Growth,1.84,False

In [20]:
data['expense_ratio_pct'] = pd.to_numeric(data['expense_ratio_pct'], errors='coerce')

In [21]:
out_of_range = data[(data['expense_ratio_pct'] <0.1) | (data['expense_ratio_pct']>2.5)]
print(f"out of range expense ratios : {len(out_of_range)}")

out of range expense ratios : 0

In [22]:
if len(out_of_range)>0:
    print(out_of_range[['scheme_name','expense_ratio_pct']])
else:
    print("All expense ratios within 0.1% - 2.5% range.")

All expense ratios within 0.1% - 2.5% range.

In [23]:
print(data.isnull().sum())

amfi_code               0
scheme_name             0
fund_house              0
category                0
plan                    0
return_1yr_pct          0
return_3yr_pct          0
return_5yr_pct          0
benchmark_3yr_pct       0
alpha                   0
beta                    0
sharpe_ratio            0
sortino_ratio           0
std_dev_ann_pct         0
max_drawdown_pct        0
aum_crore               0
expense_ratio_pct       0
morningstar_rating      0
risk_grade              0
negative_Sharpe_flag    0
dtype: int64

In [25]:
data.to_csv("C:/Users/vaishnavi/Downloads/Fintech_Capstone_Project/data/processed/clean_performance.csv")
print(data.shape)

(40, 20)